### PR TITLE
Upgrade to `go-car` `v2.0.0-beta1` tag

### PR DESCRIPTION
**Pull request by masih**
Update dependency to latest tagged release of `go-car`:
 * Fix breaking change to read option.
 * Fix breaking changes to CARv2 `index` package in tests.

Run `go mod tidy`

Relates to:
 - https://github.com/ipld/go-car/releases/tag/v2.0.0-beta1

### CODE REVIEW

**Review by raulk — APPROVED** [review]

**Comment by Stebalien** [comment]
That tag was not on master and the commit does not exist.

**Comment by Stebalien** [comment]
Hm. Scratch that, was the tag force-pushed?

**Comment by Stebalien** [comment]
```
go: github.com/filecoin-project/dagstore@v0.4.2 requires
	github.com/ipld/go-car/v2@v2.0.0-beta1.0.20210721090610-5a9d1b217d25: invalid version: unknown revision 5a9d1b217d25
go: github.com/filecoin-project/dagstore@v0.4.2 requires
	github.com/ipld/go-car/v2@v2.0.0-beta1.0.20210721090610-5a9d1b217d25: invalid version: unknown revision 5a9d1b217d25
```

**Comment by Stebalien** [comment]
Nvm, it was broken in https://github.com/filecoin-project/dagstore/pull/70.

**Pull request merged**
