### PR TITLE
Ignore nil channels in the dispatcher

### PR DESCRIPTION
**Pull request by aarshkshah1992**
If the code directly writes to the channel that the `dispatcher` function is reading from, we could escape the nil channel check we've put in place in the `dispatchResult` function.

### CODE REVIEW

**Review by raulk — APPROVED** [review]

**Review by raulk — COMMENTED** [review]
Should probably add a small test, though.

**Comment by aarshkshah1992** [comment]
Have added a test and merging as CI is green.

**Comment by Stebalien** [comment]
Please don't update to commits on random branches. We _delete_ random branches.

**Comment by Stebalien** [comment]
Tagged https://github.com/ipld/go-car/releases/tag/v2.0.0-beta2 to revive the commit.

**Pull request merged**
